### ISSUE TITLE
Cannot Install 

### ISSUE THREAD

**Issue by XINGXING-ZHANG** [tomjanus/reemission#45]
Respect for your sharing！
Pypi does not have reemission.
What‘s version of python you have used when Install from loca source？
I have try all Install methods. Cannot install still.

**Comment by tomjanus** [comment]
@XINGXING-ZHANG let me look into this over the weekend as this issue (#44) should have been fixed long time ago.
For now, I can suggest the following workaround:
Please git clone, e.g. 
`git clone git@github.com:tomjanus/reemission.git`
or
`git clone https://github.com/tomjanus/reemission.git`
depending on your git/github setup
and in the main directory where setup.py and setup.cfg are located,
please run: `pip install -e .`
This should install reemission in the editable mode, i.e. Python interpreter will read files directly from the repository.
I shall fix the remaining problems in the next couple of days.

**Comment by XINGXING-ZHANG** [comment]
Thanku for reply. But when I use reemission --help. It keeps prompting for missing and error-prone components, including various libraries being absent, and issues arising from code version discrepancies due to Python versions. One fix leads to another, and so on.
<img width="465" alt="1713069114452" src="https://github.com/tomjanus/reemission/assets/57533177/3fd55c43-6459-49c9-82db-6ccc4834f3ef">

**Comment by XINGXING-ZHANG** [comment]
and so on
<img width="465" alt="1713069437746" src="https://github.com/tomjanus/reemission/assets/57533177/ee18b92f-2fb6-4af2-bf7a-a86f7e24137f">

**Comment by XINGXING-ZHANG** [comment]
continue
<img width="586" alt="1713077254113" src="https://github.com/tomjanus/reemission/assets/57533177/d766c13a-3458-48c8-b4e8-003e79aa4cb3">

**Comment by XINGXING-ZHANG** [comment]
After fix one by one. It works now. Thank for u nice work [tomjanus](https://github.com/tomjanus)
TypeError: The following constraints cannot be applied to typing.List[float]: 'ge'
"""
    area_fractions: List[float] = Field(
        ge=0, description="Inundated area fractions of landuse types, -", 
        default_factory=list)
    """
    area_fractions: conlist(
        confloat(ge=0), description="Inundated area fractions of landuse types, -", default_factory=list
    ) = Field(
        description="Inundated area fractions of landuse types, -", 
        default_factory=list)
 """
    area_fractions: List[float] = Field(
        ge=0, description="Area fractions of landuse types, -", 
        default_factory=list)
    """  
    area_fractions: conlist(
        confloat(ge=0), description="Area fractions of landuse types, -", default_factory=list
    ) = Field(
        ..., description="Area fractions of landuse types, -", 
        default_factory=list)    
<img width="586" alt="1713077986000" src="https://github.com/tomjanus/reemission/assets/57533177/6d89ba93-3ca4-4572-b8be-e374223a1055">

**Comment by XINGXING-ZHANG** [comment]
Still have some problem, when run-demo. @tomjanus 
$ reemission run-demo
C:\Users\User\anaconda3\Lib\site-packages\pydantic\_internal\_config.py:334: UserWarning: Valid config
 keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'fields' has been removed
  warnings.warn(message, UserWarning)
 ____  _____      _____           _         _
|  _ \| ____|    | ____|_ __ ___ (_)___ ___(_) ___  _ __
| |_) |  _| _____|  _| | '_ ` _ \| / __/ __| |/ _ \| '_ \
|  _ <| |__|_____| |___| | | | | | \__ \__ \ | (_) | | | |
|_| \_\_____|    |_____|_| |_| |_|_|___/___/_|\___/|_| |_|


RUNNING CALCULATIONS FOR A SUBSET OF EXISTING AND FUTURE HYDROELECTRIC RESERVOIRS IN MYANMAR...

1. Fetching the demo dabase of dams from external sources...
The DAMS database folder C:\Users\User\reemission\examples\demo\reemission_demo_dam_db exists and has
the correct size.
Fetching the dam database from external sources not required.

2. Fetching reservoir and catchment delineations from external sources...
The DAMS database folder C:\Users\User\reemission\examples\demo\reemission_demo_delineations exists an
d has the correct size.
Fetching the dam database from external sources not required.

3. Creating the outputs folder C:\Users\User\reemission\examples\demo\heet_outputs ...
Folder already exists: C:\Users\User\reemission\examples\demo\heet_outputs

4. Merging tabular data into a single CSV file and saving to C:\Users\User\reemission\examples\demo\he
et_outputs\heet_outputs.csv ...
C:\Users\User\anaconda3\Lib\site-packages\pydantic\_internal\_config.py:334: UserWarning: Valid config
 keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'fields' has been removed
  warnings.warn(message, UserWarning)
Adding column: c_treatment_factor with value primary (mechanical) to data in file(s) C:\Users\User\ree
mission\examples\demo\reemission_demo_delineations\batch_1\output_parameters.csv, C:\Users\User\reemis
sion\examples\demo\reemission_demo_delineations\batch_2\output_parameters.csv, C:\Users\User\reemissio
n\examples\demo\reemission_demo_delineations\batch_3\output_parameters.csv, C:\Users\User\reemission\e
xamples\demo\reemission_demo_delineations\batch_4\output_parameters.csv
Adding column: c_landuse_intensity with value low intensity to data in file(s) C:\Users\User\reemissio
n\examples\demo\reemission_demo_delineations\batch_1\output_parameters.csv, C:\Users\User\reemission\e
xamples\demo\reemission_demo_delineations\batch_2\output_parameters.csv, C:\Users\User\reemission\exam
ples\demo\reemission_demo_delineations\batch_3\output_parameters.csv, C:\Users\User\reemission\example
s\demo\reemission_demo_delineations\batch_4\output_parameters.csv
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\anaconda3\Scripts\reemission-heet.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\rich_click\rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\reemission\src\reemission\integration\cli\cli.py", line 95, in process_tab_outpu
ts
    heet_output.filter_columns(
  File "C:\Users\User\reemission\src\reemission\integration\heet\heet_tab_parser.py", line 161, in fil
ter_columns
    raise ColumnsNotFoundError(missing_mandatory)
reemission.integration.heet.custom_exceptions.ColumnsNotFoundError: Missing columns type

5. Merging shape files for individual reservoirs into combined shape files...
C:\Users\User\anaconda3\Lib\site-packages\pydantic\_internal\_config.py:334: UserWarning: Valid config
 keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'fields' has been removed
  warnings.warn(message, UserWarning)
Concatenating shape files matching pattern R_*.shp.
Concatenating shapes for dam ids 33, 35, 101, 8, 9, 107, 47, 151, 120, 152, 127.
Data saved to shape file C:\Users\User\reemission\examples\demo\heet_outputs\reservoirs.shp.
Concatenating shape files matching pattern C_*.shp.
Concatenating shapes for dam ids 33, 35, 101, 8, 9, 107, 47, 151, 120, 152, 127.
Data saved to shape file C:\Users\User\reemission\examples\demo\heet_outputs\catchments.shp.
Concatenating shape files matching pattern MS_*.shp.
Concatenating shapes for dam ids 33, 35, 101, 8, 9, 107, 47, 151, 120, 152, 127.
Data saved to shape file C:\Users\User\reemission\examples\demo\heet_outputs\rivers.shp.
Concatenating shape files matching pattern PS_*.shp.
Concatenating shapes for dam ids 33, 35, 101, 8, 9, 107, 47, 151, 120, 152, 127.
Data saved to shape file C:\Users\User\reemission\examples\demo\heet_outputs\dams.shp.

6. Converting HEET tabular data to the RE-Emission input JSON file
C:\Users\User\anaconda3\Lib\site-packages\pydantic\_internal\_config.py:334: UserWarning: Valid config
 keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'fields' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\anaconda3\Scripts\reemission-heet.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\rich_click\rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\reemission\src\reemission\integration\cli\cli.py", line 176, in tab_to_json
    converter.to_json(pathlib.Path(output_file))
  File "C:\Users\User\reemission\src\reemission\integration\heet\heet_tab_to_json.py", line 120, in to
_json
    heet_output = TabularHeetOutput.from_csv(self.tab_data_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\reemission\src\reemission\integration\heet\heet_tab_parser.py", line 124, in fro
m_csv
    df_ = pd.read_csv(filename)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init_
_
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_e
ngine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\reemission\\examples\\demo\\
heet_outputs\\heet_outputs.csv'

7. Creating the outputs folder C:\Users\User\reemission\examples\demo\reemission_outputs ...
Folder already exists: C:\Users\User\reemission\examples\demo\reemission_outputs

8. Calculating GHG emissions with RE-EMISSION
C:\Users\User\anaconda3\Lib\site-packages\pydantic\_internal\_config.py:334: UserWarning: Valid config
 keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'fields' has been removed
  warnings.warn(message, UserWarning)
 ____  _____      _____           _         _
|  _ \| ____|    | ____|_ __ ___ (_)___ ___(_) ___  _ __
| |_) |  _| _____|  _| | '_ ` _ \| / __/ __| |/ _ \| '_ \
|  _ <| |__|_____| |___| | | | | | \__ \__ \ | (_) | | | |
|_| \_\_____|    |_____|_| |_| |_|_|___/___/_|\___/|_| |_|



 Usage: reemission calculate [OPTIONS] INPUT_FILE

 Try 'reemission calculate --help' for help
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for 'INPUT_FILE': Path                                                               │
│ 'C:\\Users\\User\\reemission\\examples\\demo\\heet_outputs\\reemission_inputs.json' does not       │
│ exist.                                                                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────────────╯


9. Merging input and output data into shape files
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\anaconda3\Scripts\reemission.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\rich_click\rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\reemission\src\reemission\cli\cli.py", line 377, in run_demo
    process_mya_case_study_results(
  File "C:\Users\User\reemission\examples\demo\postprocess_results.py", line 22, in process_mya_case_s
tudy_results
    append_data_to_shapes(shp_folder, data_file, config)
  File "C:\Users\User\reemission\src\reemission\postprocessing\data_processing.py", line 179, in appen
d_data_to_shapes
    tab_data = load_csv(data_file)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\reemission\src\reemission\utils.py", line 94, in load_csv
    return pd.read_csv(path)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init_
_
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_e
ngine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\reemission\\examples\\demo\\
heet_outputs\\heet_outputs.csv'

**Comment by XINGXING-ZHANG** [comment]
@tomjanus in step 4, the error happened

**Comment by tomjanus** [comment]
@XINGXING-ZHANG I suspect you've fixed the installation issues with missing rich-click package and with lack os support for pydantic v2. The dependency needs to be down,graded to v1. I shall update the repository shortly, including setuptools, the demo and the jupyter notebooks which are outdated due to some recent developments - mainly new input variables and input data templating with pydantic. Thank you for your patience.

**Comment by tomjanus** [comment]
Fixed in #[74a7974](https://github.com/tomjanus/reemission/commit/74a7974a0b25cd388c719f3d2095f8c6675ae911)
